name: "Terraform deployment"
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs: 
  terraform: 
    name: "Terraform provision"
    runs-on: ubuntu-latest
    steps:
      #check out the terraform repo code 
      - name: 'Checkout tf source code'
        uses: actions/checkout@v3
      
      # setup terraform cli 
      - name: "TF enginee Setup"
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.3
          terraform_wrapper: false
      - name: "Init tf"
        run: "terraform init"

      - name: "Get tf workspace and create the workspace"
        run: "terraform workspace new prod"
      
      - name: "Checkout namespace"
        run: "terraform workspace select prod"

      - name: "Verify the prod tfvars "
        run: "terraform plan -var-file=./envs/prod.tfvars"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

      